# Generated by Django 3.0.8 on 2020-07-19 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sekce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
                ('poradi', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sekce',
                'verbose_name_plural': 'Sekce',
            },
        ),
        migrations.CreateModel(
            name='Vlakno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('vytvoreno', models.DateTimeField()),
                ('materska_sekce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wwwforum.Sekce')),
            ],
            options={
                'verbose_name': 'Vlákno',
                'verbose_name_plural': 'Vlákna',
            },
        ),
        migrations.CreateModel(
            name='Prispevek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsah', models.CharField(max_length=500)),
                ('vytvoreno', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materske_vlakno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwwforum.Vlakno')),
            ],
            options={
                'verbose_name': 'Příspěvek',
                'verbose_name_plural': 'Příspěvky',
            },
        ),
    ]
