# Generated by Django 3.0.8 on 2020-07-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prispevek',
            name='vytvoreno',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sekce',
            name='poradi',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vlakno',
            name='vytvoreno',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
