# Generated by Django 3.0.8 on 2020-07-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforum', '0002_auto_20200720_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prispevek',
            name='obsah',
            field=models.TextField(max_length=500),
        ),
    ]
